In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set();

# adding for openning .xlsx file
# !pip install openpyxl

In [2]:
data = pd.read_excel('DATA.xlsx', sheet_name=0)

/tmp/ipykernel_46504/402831475.py:1: FutureWarning: Inferring datetime64[ns] from data containing strings is deprecated and will be removed in a future version. To retain the old behavior explicitly pass Series(data, dtype=datetime64[ns])
  data = pd.read_excel('DATA.xlsx', sheet_name=0)

In [3]:
data.head(10)

,id точки,Адрес,Широта,Долгота,Дата открытия,Дата закрытия,Площадь магазина,Тип входа,Площадь ТЦ,Формат магазина,...,Этаж,Время работы,Заполненность ТЦ,Рядом с эскалатором,Рядом со входом,Конкуренты в ТЦ,Расположение в ТЦ,Толока,Люкс,Выборка
0,8955.0,"Оренбургская обл, Оренбург г, Шарлыкское ш, д...",55.118272,51.843127,2016-11-09 00:00:00,NaT,478,без сквозного прохода,130000.0,ТЦ,...,3,с 10:00 до 22:00,NaN,0,0,1.0,7.0,37.857582,69.500000,Обучающая
1,11007.0,"Алтайский край, г. Барнаул, ул. Малахова, дом ...",83.696799,53.356954,2010-04-26 00:00:00,NaT,332,сквозной проход,31500.0,ТЦ,...,1,с 10:00 до 22:00,NaN,0,1,NaN,9.0,57.810494,66.896552,Обучающая
2,11366.0,"Амурская область, Благовещенск, улица Мухина, 114",127.510357,50.280435,2017-08-25 00:00:00,NaT,356,без сквозного прохода,36000.0,ТЦ,...,1,с 10:00 до 22:00,3.0,0,1,1.0,6.0,49.959831,68.727273,Обучающая
3,11810.0,"Архангельская обл, г. Архангельск , Троицкий п...",40.528249,64.532316,2012-11-03 00:00:00,NaT,317,отдельный вход с улицы + сквозной проход,35000.0,ТЦ,...,1,с 10:00 до 21:00,3.0,0,1,0.0,10.0,128.459158,64.517241,Обучающая
4,15041.0,"Архангельская обл, г. Архангельск, Троицкий пр...",40.526317,64.534327,2006-12-09 00:00:00,NaT,176,сквозной проход,15332.0,ТЦ,...,цоколь,с 10:00 до 21:00,3.0,1,0,NaN,0.0,103.199885,78.275862,Тестовая
5,15087.0,"Архангельская обл, г. Архангельск, ул. Воскрес...",40.535400,64.541900,2014-11-20 00:00:00,NaT,416,без сквозного прохода,60000.0,ТЦ,...,1,с 10:00 до 21:00,3.0,1,1,NaN,10.5,71.418989,67.035714,Тестовая
6,15621.0,"Архангельская обл, г. Северодвинск, ул. Ломоно...",39.785522,64.550364,2003-11-09 00:00:00,NaT,178,сквозной проход,20000.0,ТЦ,...,1,с 10:00 до 21:00,3.0,0,0,0.0,8.0,82.880454,64.034483,Обучающая
7,15775.0,"Астраханская обл, г. Астрахань, ул. Боевая, до...",48.023172,46.338313,2014-02-05 00:00:00,NaT,521,без сквозного прохода,130000.0,ТЦ,...,1,с 10:00 до 22:00,NaN,0,1,1.0,8.0,38.935806,62.827586,Обучающая
8,16102.0,"Барнаул г, Ленина пр-кт, дом № 102В, ТЦ ""Пионер""",83.764275,53.362114,2017-06-07 00:00:00,NaT,369,отдельный вход с улицы + сквозной проход,80000.0,ТЦ,...,1,с 10:00 до 22:00,0.0,0,0,0.0,1.5,27.525274,65.500000,Обучающая
9,16119.0,"Башкортостан Респ, Уфа г, Цюрупы ул, дом № 97 ...",55.958263,54.736556,2018-05-23 00:00:00,NaT,662,сквозной проход,48000.0,ТЦ,...,1,с 10:00 до 22:00,3.0,1,1,NaN,10.0,83.191620,71.428571,Тестовая

In [4]:
data.shape

(246, 21)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id точки             245 non-null    float64
 1   Адрес                246 non-null    object
 2   Широта               242 non-null    float64
 3   Долгота              242 non-null    float64
 4   Дата открытия        245 non-null    object
 5   Дата закрытия        9 non-null      datetime64[ns]
 6   Площадь магазина     246 non-null    int64
 7   Тип входа            244 non-null    object
 8   Площадь ТЦ           204 non-null    float64
 9   Формат магазина      246 non-null    object
 10  Парковка             226 non-null    object
 11  Этаж                 241 non-null    object
 12  Время работы         232 non-null    object
 13  Заполненность ТЦ     182 non-null    float64
 14  Рядом с эскалатором  246 non-null    int64
 15  Рядом со входом      246 non-null    int64
 16  Конкуренты в ТЦ      94 non-null     float64
 17  Расположение в ТЦ    224 non-null    float64
 18  Толока               246 non-null    float64
 19  Люкс                 246 non-null    float64
 20  Выборка              245 non-null    object
dtypes: datetime64[ns](1), float64(9), int64(3), object(8)
memory usage: 40.5+ KB

In [6]:
data.describe()

,id точки,Широта,Долгота,Площадь магазина,Площадь ТЦ,Заполненность ТЦ,Рядом с эскалатором,Рядом со входом,Конкуренты в ТЦ,Расположение в ТЦ,Толока,Люкс
count,2.450000e+02,242.000000,242.000000,246.000000,204.000000,182.000000,246.000000,246.000000,94.000000,224.000000,246.000000,246.000000
mean,1.132649e+05,47.270235,55.692249,380.837398,69561.509804,2.472527,0.451220,0.487805,0.776596,8.042411,56.703189,69.644964
std,4.332589e+05,24.447551,5.587842,206.211319,67128.326340,0.858376,0.506749,0.540081,0.705649,2.911510,35.526801,12.816096
min,8.955000e+03,20.500255,43.019324,91.000000,700.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.454353,36.724138
25%,4.201100e+04,33.383124,53.376779,251.000000,19958.500000,2.000000,0.000000,0.000000,0.000000,6.000000,32.953392,61.974138
50%,4.230600e+04,37.893216,55.794705,330.000000,47800.000000,3.000000,0.000000,0.000000,1.000000,8.000000,49.812128,69.287356
75%,4.260800e+04,50.118003,59.832158,429.750000,103455.750000,3.000000,1.000000,1.000000,1.000000,10.000000,69.030800,75.689655
max,2.633948e+06,158.662682,91.758249,1488.000000,396000.000000,3.000000,2.000000,3.000000,3.000000,14.000000,248.234096,124.241379

# Data Cleaning

In [7]:
#missing data

total = data.isnull().sum().sort_values(ascending=False)
percent = (data.isnull().sum() / data.isnull().count()).sort_values(ascending=False)

missing_data = pd.concat([total, percent], axis=1, keys=['total', 'percent'])

Сначала нужно проверить количество пропущенных значений в каждом столбце и процент отсутствующих значений, на который они влияют.

In [8]:
missing_data

                     total   percent
Дата закрытия          237  0.963415
Конкуренты в ТЦ        152  0.617886
Заполненность ТЦ        64  0.260163
Площадь ТЦ              42  0.170732
Расположение в ТЦ       22  0.089431
Парковка                20  0.081301
Время работы            14  0.056911
Этаж                     5  0.020325
Широта                   4  0.016260
Долгота                  4  0.016260
Тип входа                2  0.008130
id точки                 1  0.004065
Дата открытия            1  0.004065
Выборка                  1  0.004065
Адрес                    0  0.000000
Формат магазина          0  0.000000
Рядом с эскалатором      0  0.000000
Рядом со входом          0  0.000000
Площадь магазина         0  0.000000
Толока                   0  0.000000
Люкс                     0  0.000000

Всего мы имеем 246 различных наборов значений. Из столбца "Дата закрытия" мы имеем отсутствие почти 97% данных, для нашей будующей модели это может оказаться критичным, т.к. дата закрытия может коррелировать с остальными значениями.
Из столбца "Конкуренты в  ТЦ" у нас также отсутствует много значений, а конкретно почти 62%. Если смотреть с точки зрения посещаемости, то начилие тех или иных конкурентов для посещения определенного магазины имеет критически важное значение. Далее из того, что привлекает сразу в наборе missing_data - это Заполненность в ТЦ и Площадь ТЦ (последние 2 признака, которые имеют большое недоставание по данным). Заполненность ТЦ и Площадь ТЦ имеют также ключевое значение для посещаемости, т.к. смотря на статистику, людям интереснее в своем большинстве ходить в более крупные ТЦ, в которых имеется большой выбор товаров, которые их интерресуют, из этого может вытекать и заполненность ТЦ. 
Можно сделать предварительные выводы о том, что необходимо дополнить следующие столбцы:
1) Дату закрытия, как минимум на 81%;
2) Конкурентов в ТЦ, как минимум на 47%;
3) Заполненность ТЦ, как минимум на 12%;
4) Площадь ТЦ на минимум 2-3%.

Кроме того, столбцы признаков "Расположение в ТЦ", "Парковка" и "Время работы" также имеют много отсутствующих значений.
В идеале дополнить все столбцы, начиная с "Даты закрытия" и заканчивая "Этажом".
Теперь можно попробовать посмотреть на корреляцию признаков между собой.

In [9]:
# Можем удалить столбец Адрес, т.к. у нас есть столбец с 
# ID точки, которого нам хватает.
# И также уберем столбец Выборка, т.к. это нам сейчас не важно.
data = data.drop(columns=['Адрес', 'Выборка'])

In [10]:
data = data.replace({'Парковка':{'100': "бесплатная парковка",}})
data['Парковка'].fillna('нет парквоки', inplace=True)

In [11]:
# Затем у нас есть другие данные которые необходимо преобразовать.
# Тип входа, парковка, формат магазина и время работы надо преобразовать, для этого давайте закодируем их значения

from sklearn.preprocessing import OrdinalEncoder

ord_enc = OrdinalEncoder()

data['Entranse type'] = ord_enc.fit_transform(data[['Тип входа']])

In [12]:
data['Парковка'] = data['Парковка'].astype('str')

In [13]:
data['Parking'] = ord_enc.fit_transform(data[['Парковка']])

In [14]:
data['Magazine Format'] = ord_enc.fit_transform(data[['Формат магазина']])

In [15]:
data['Working time'] = ord_enc.fit_transform(data[['Время работы']])

In [16]:
data = data.drop(columns=['Тип входа', 'Парковка', 'Формат магазина', 'Время работы', ])

In [17]:
data = data.replace({'Этаж':{'цоколь': 0,
                             '02.май': 2}})

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id точки             245 non-null    float64
 1   Широта               242 non-null    float64
 2   Долгота              242 non-null    float64
 3   Дата открытия        245 non-null    object
 4   Дата закрытия        9 non-null      datetime64[ns]
 5   Площадь магазина     246 non-null    int64
 6   Площадь ТЦ           204 non-null    float64
 7   Этаж                 241 non-null    object
 8   Заполненность ТЦ     182 non-null    float64
 9   Рядом с эскалатором  246 non-null    int64
 10  Рядом со входом      246 non-null    int64
 11  Конкуренты в ТЦ      94 non-null     float64
 12  Расположение в ТЦ    224 non-null    float64
 13  Толока               246 non-null    float64
 14  Люкс                 246 non-null    float64
 15  Entranse type        244 non-null    float64
 16  Parking              246 non-null    float64
 17  Magazine Format      246 non-null    float64
 18  Working time         232 non-null    float64
dtypes: datetime64[ns](1), float64(13), int64(3), object(2)
memory usage: 36.6+ KB

In [19]:
data['Дата закрытия'] = pd.to_numeric(pd.to_datetime(data['Дата закрытия']))
data['Дата открытия'] = pd.to_numeric(pd.to_datetime(data['Дата открытия']))

/tmp/ipykernel_46504/2136430192.py:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  data['Дата открытия'] = pd.to_numeric(pd.to_datetime(data['Дата открытия']))

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id точки             245 non-null    float64
 1   Широта               242 non-null    float64
 2   Долгота              242 non-null    float64
 3   Дата открытия        246 non-null    int64
 4   Дата закрытия        246 non-null    int64
 5   Площадь магазина     246 non-null    int64
 6   Площадь ТЦ           204 non-null    float64
 7   Этаж                 241 non-null    object
 8   Заполненность ТЦ     182 non-null    float64
 9   Рядом с эскалатором  246 non-null    int64
 10  Рядом со входом      246 non-null    int64
 11  Конкуренты в ТЦ      94 non-null     float64
 12  Расположение в ТЦ    224 non-null    float64
 13  Толока               246 non-null    float64
 14  Люкс                 246 non-null    float64
 15  Entranse type        244 non-null    float64
 16  Parking              246 non-null    float64
 17  Magazine Format      246 non-null    float64
 18  Working time         232 non-null    float64
dtypes: float64(13), int64(5), object(1)
memory usage: 36.6+ KB

Для того, чтобы посмотреть на корреляцию значений мы перекодировали стрововые данные и заменили некорректные.
Например, в столбце "Этаж" было значение "02.май", такого допускать нельзя.
Пронаблюдаем за корреляцией

In [21]:
df_1 = data.corr()

/tmp/ipykernel_46504/85035698.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_1 = data.corr()

In [26]:
df_1

,id точки,Широта,Долгота,Дата открытия,Дата закрытия,Площадь магазина,Площадь ТЦ,Заполненность ТЦ,Рядом с эскалатором,Рядом со входом,Конкуренты в ТЦ,Расположение в ТЦ,Толока,Люкс,Entranse type,Parking,Magazine Format,Working time
id точки,1.000000,0.130501,0.123183,0.012228,-0.033214,0.066075,-0.037028,0.023602,-0.009575,0.024331,0.155025,-0.012940,-0.087177,-0.102118,-0.106912,-0.050836,-0.042147,0.031088
Широта,0.130501,1.000000,-0.179369,-0.215014,-0.066121,0.264309,-0.093925,-0.037458,-0.006899,-0.066926,0.097515,-0.001064,-0.128051,-0.120540,-0.046267,-0.195263,0.093937,0.004410
Долгота,0.123183,-0.179369,1.000000,0.005994,0.067549,-0.057616,-0.035838,0.107282,0.114715,0.019019,-0.042902,0.054973,0.049162,0.022680,0.045312,0.007241,0.026627,0.022443
Дата открытия,0.012228,-0.215014,0.005994,1.000000,-0.001783,-0.154499,0.046729,-0.047627,0.072127,0.078930,-0.058012,0.025426,0.002081,0.020516,-0.080113,-0.051336,0.020389,-0.018972
Дата закрытия,-0.033214,-0.066121,0.067549,-0.001783,1.000000,-0.047645,-0.020247,0.089830,0.040340,0.024518,0.180743,0.020485,-0.080624,-0.091084,0.006182,-0.001922,0.010022,-0.050844
Площадь магазина,0.066075,0.264309,-0.057616,-0.154499,-0.047645,1.000000,0.168191,-0.124903,0.050779,-0.008374,0.295619,0.128708,-0.102009,0.009044,-0.040229,-0.142289,0.194942,-0.088497
Площадь ТЦ,-0.037028,-0.093925,-0.035838,0.046729,-0.020247,0.168191,1.000000,0.057706,0.010401,-0.139338,0.361026,0.113527,0.136717,0.186127,-0.085379,-0.119863,0.319723,-0.234677
Заполненность ТЦ,0.023602,-0.037458,0.107282,-0.047627,0.089830,-0.124903,0.057706,1.000000,0.151653,-0.011839,0.189140,0.297781,0.161348,0.111956,0.024723,0.070228,-0.029048,-0.059513
Рядом с эскалатором,-0.009575,-0.006899,0.114715,0.072127,0.040340,0.050779,0.010401,0.151653,1.000000,0.191694,0.048525,0.281538,0.100987,0.016541,-0.117173,-0.008901,0.168494,0.069458
Рядом со входом,0.024331,-0.066926,0.019019,0.078930,0.024518,-0.008374,-0.139338,-0.011839,0.191694,1.000000,-0.199917,0.155129,0.025242,0.028355,0.095670,-0.046046,0.029314,0.049637
Конкуренты в ТЦ,0.155025,0.097515,-0.042902,-0.058012,0.180743,0.295619,0.361026,0.189140,0.048525,-0.199917,1.000000,0.236066,0.026670,-0.050291,-0.255209,0.086075,0.207100,-0.011801
Расположение в ТЦ,-0.012940,-0.001064,0.054973,0.025426,0.020485,0.128708,0.113527,0.297781,0.281538,0.155129,0.236066,1.000000,0.134271,0.037403,-0.049063,0.015119,0.222923,0.006705
Толока,-0.087177,-0.128051,0.049162,0.002081,-0.080624,-0.102009,0.136717,0.161348,0.100987,0.025242,0.026670,0.134271,1.000000,0.562568,0.087092,0.208606,0.231682,0.000821
Люкс,-0.102118,-0.120540,0.022680,0.020516,-0.091084,0.009044,0.186127,0.111956,0.016541,0.028355,-0.050291,0.037403,0.562568,1.000000,0.047998,0.144720,0.097982,-0.102624
Entranse type,-0.106912,-0.046267,0.045312,-0.080113,0.006182,-0.040229,-0.085379,0.024723,-0.117173,0.095670,-0.255209,-0.049063,0.087092,0.047998,1.000000,0.188731,-0.154200,0.030799
Parking,-0.050836,-0.195263,0.007241,-0.051336,-0.001922,-0.142289,-0.119863,0.070228,-0.008901,-0.046046,0.086075,0.015119,0.208606,0.144720,0.188731,1.000000,-0.197273,0.026756
Magazine Format,-0.042147,0.093937,0.026627,0.020389,0.010022,0.194942,0.319723,-0.029048,0.168494,0.029314,0.207100,0.222923,0.231682,0.097982,-0.154200,-0.197273,1.000000,0.034563
Working time,0.031088,0.004410,0.022443,-0.018972,-0.050844,-0.088497,-0.234677,-0.059513,0.069458,0.049637,-0.011801,0.006705,0.000821,-0.102624,0.030799,0.026756,0.034563,1.000000

# Письмо

Дорогому заказчику.

Здравствуйте, меня зовут Сергей, и я junior data scientist, который работает с вашими данными.
В дальнейшем, по вашим запросам будет создана соответствубщая модель, которая будет анализировать
все ваши личные данные. Но она не сможет быть достаточно правильной, даже наоборот ложной из-за
определенных недостатков в качестве данных. Я бы хотел указать на определенные моменты, которые
помогут нам добиться вместе с вами максимального результата, и создать для вас максимально результативную
модель, которая поможет вам в ваших проектах. 
Среди присланных вами ранее данных я могу выделить следующие нелочеты:
    1. У названий колонок, в последствии которые станут признаками нашей модели недостает конкретики, 
    а именно размерности, например для площади это матры квадратные, а для выручки того, в какой валюте
    была измерена непосредственно выручка и в каком объеме, могу предположить что там в тысячах у.е. но для
    результативности лучше указываться либо в названии признака либо создавать сопроводительное письмо, 
    в котором будет отражен характер всех измеренных вами величин.
    2. Формат данных. Например если брать данные из колонки "Формат магазина", то можно заметить, 
    что например одни и теже данные по сути отражены разными величинами, например "Street" и "Стрит", 
    нам с вами понятно, что это одно и тоже, но модели может такой расхождение не пойти на пользу.
    3. Если вы пишете, напрмер, для этажа цифру, то неоюходимо писать далее цифру, тогда этажи типа "Цоколь"
    и "02.май" можно заменить на "0" этаж или "-1" и т.д.
    4. Тип парковки не можеть быть цифровой, вероятно вы имели ввиду цену за парковку, но тогда неоюходимо
    относительно выших данных писать "планая парковка", прочая информация излишне.
    5.Относительно данных по выручке для обучающей выборки. Очень много пропущенных значаний. Скореее всего 
    магазины открывались постепенно и поэтому такой градиент выручки, но среди данных имеется "###", возможно
    были сбои, следует разобраться почему за данные месяца не отображена выручка, а для в принципе
    отстутствующих значений необходимо перепроверить подлинность и поставить "NaN".
    6. Все столбцы предлагаю прописывать латиницей (Английскими буквами).
    7. Данные по адресу могут быть удаленны.С помощью широты и долготы, по индексу точки будет хватать,
    чтобы определить адрес магазины. ТАким образом получится убрать лишнюю информацию.
    8. Проработать информацию об магазинах. В странице файла экселя с информацией о точках очень много пропущенных
    ячеек, которые могли бы вносить больше смысла в данные. Стоит разобраться, почему у вас там такое большое 
    количество пропусков и проработать данный момент.
Вышеперечисленные замечвания и пожелания я считаю исчерпывающими. Надеюсь на выше понимание. 
Junior Data scientist
Сергей